In [394]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler,StandardScaler,LabelEncoder,OneHotEncoder,OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [395]:
df=pd.read_csv("heart_disease.csv")

In [396]:
df

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,NaN,High,NaN,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,NaN,Female,NaN,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,NaN,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

In [397]:
one=df.select_dtypes(include="object")
one

,Gender,Exercise Habits,Smoking,Family Heart Disease,Diabetes,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sugar Consumption,Heart Disease Status
0,Male,High,NaN,Yes,No,Yes,Yes,No,High,Medium,Medium,No
1,Female,High,No,Yes,Yes,No,Yes,No,Medium,High,Medium,No
2,Male,Low,No,No,No,No,Yes,Yes,Low,Low,Low,No
3,NaN,High,Yes,Yes,No,Yes,No,Yes,Low,High,High,No
4,Male,Low,Yes,Yes,Yes,Yes,No,No,Low,High,High,No
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Female,Medium,Yes,No,No,Yes,No,Yes,Medium,High,Medium,Yes
9996,Male,Medium,No,No,No,Yes,No,Yes,NaN,High,Low,Yes
9997,Male,High,Yes,No,Yes,No,Yes,Yes,NaN,Low,Low,Yes
9998,Male,Low,Yes,No,Yes,Yes,No,Yes,Medium,High,Medium,Yes
9999,Female,Medium,Yes,Yes,Yes,No,Yes,Yes,High,Medium,High,Yes

In [398]:
df.select_dtypes(include="number").columns

Index(['Age', 'Blood Pressure', 'Cholesterol Level', 'BMI', 'Sleep Hours',
       'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level',
       'Homocysteine Level'],
      dtype='object')

In [399]:
one.columns

Index(['Gender', 'Exercise Habits', 'Smoking', 'Family Heart Disease',
       'Diabetes', 'High Blood Pressure', 'Low HDL Cholesterol',
       'High LDL Cholesterol', 'Alcohol Consumption', 'Stress Level',
       'Sugar Consumption', 'Heart Disease Status'],
      dtype='object')

In [400]:
# Columns for ordinal encoding
ordinal_cols = ['Exercise Habits','Alcohol Consumption','Stress Level','Sugar Consumption']

# Columns for one-hot encoding
onehot_cols =['Gender','Smoking','Family Heart Disease',
       'Diabetes', 'High Blood Pressure', 'Low HDL Cholesterol',
       'High LDL Cholesterol','Heart Disease Status']

# Perform ordinal encoding
ordinal_encoder = OrdinalEncoder()
df[ordinal_cols] = ordinal_encoder.fit_transform(df[ordinal_cols])

# Perform one-hot encoding
onehot_encoder = OneHotEncoder(drop='first',sparse_output=False)
onehot_encoded = onehot_encoder.fit_transform(df[onehot_cols])
onehot_encoded_data = pd.DataFrame(onehot_encoded, columns=onehot_encoder.get_feature_names_out(onehot_cols))

# Concatenate the one-hot encoded columns with the original dataframe
newdf = pd.concat([df.drop(onehot_cols, axis=1), onehot_encoded_data], axis=1)

newdf.head()

,Age,Blood Pressure,Cholesterol Level,Exercise Habits,BMI,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,...,Family Heart Disease_nan,Diabetes_Yes,Diabetes_nan,High Blood Pressure_Yes,High Blood Pressure_nan,Low HDL Cholesterol_Yes,Low HDL Cholesterol_nan,High LDL Cholesterol_Yes,High LDL Cholesterol_nan,Heart Disease Status_Yes
0,56.0,153.0,NaN,0.0,24.991591,0.0,2.0,7.633228,2.0,342.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1,NaN,NaN,286.0,0.0,25.221799,2.0,0.0,8.744034,2.0,133.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,46.0,126.0,216.0,1.0,29.855447,1.0,1.0,4.440440,1.0,393.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,32.0,122.0,293.0,0.0,24.130477,1.0,0.0,5.249405,0.0,293.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,60.0,166.0,242.0,1.0,20.486289,1.0,0.0,7.030971,0.0,263.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [401]:
newdf

,Age,Blood Pressure,Cholesterol Level,Exercise Habits,BMI,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,...,Family Heart Disease_nan,Diabetes_Yes,Diabetes_nan,High Blood Pressure_Yes,High Blood Pressure_nan,Low HDL Cholesterol_Yes,Low HDL Cholesterol_nan,High LDL Cholesterol_Yes,High LDL Cholesterol_nan,Heart Disease Status_Yes
0,56.0,153.0,NaN,0.0,24.991591,0.0,2.0,7.633228,2.0,342.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1,NaN,NaN,286.0,0.0,25.221799,2.0,0.0,8.744034,2.0,133.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,46.0,126.0,216.0,1.0,29.855447,1.0,1.0,4.440440,1.0,393.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,32.0,122.0,293.0,0.0,24.130477,1.0,0.0,5.249405,0.0,293.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,60.0,166.0,242.0,1.0,20.486289,1.0,0.0,7.030971,0.0,263.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,136.0,243.0,2.0,18.788791,2.0,0.0,6.834954,2.0,343.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
9996,38.0,172.0,154.0,2.0,31.856801,NaN,0.0,8.247784,1.0,377.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
9997,73.0,152.0,201.0,0.0,26.899911,NaN,1.0,4.436762,1.0,248.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
9998,23.0,142.0,299.0,1.0,34.964026,2.0,0.0,8.526329,2.0,113.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
9999,38.0,128.0,193.0,2.0,25.111295,0.0,2.0,5.659394,0.0,121.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0

In [402]:
(newdf.isna().sum() / len(newdf)) * 100

Age                          0.30
Blood Pressure               0.20
Cholesterol Level            0.31
Exercise Habits              0.25
BMI                          0.22
Alcohol Consumption         25.86
Stress Level                 0.22
Sleep Hours                  0.25
Sugar Consumption            0.30
Triglyceride Level           0.26
Fasting Blood Sugar          0.22
CRP Level                    0.26
Homocysteine Level           0.20
Gender_Male                  0.00
Gender_nan                   0.00
Smoking_Yes                  0.00
Smoking_nan                  0.00
Family Heart Disease_Yes     0.00
Family Heart Disease_nan     0.00
Diabetes_Yes                 0.00
Diabetes_nan                 0.00
High Blood Pressure_Yes      0.00
High Blood Pressure_nan      0.00
Low HDL Cholesterol_Yes      0.00
Low HDL Cholesterol_nan      0.00
High LDL Cholesterol_Yes     0.00
High LDL Cholesterol_nan     0.00
Heart Disease Status_Yes     0.00
dtype: float64

In [403]:
newdf.shape

(10000, 28)

In [404]:
newdf

,Age,Blood Pressure,Cholesterol Level,Exercise Habits,BMI,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,...,Family Heart Disease_nan,Diabetes_Yes,Diabetes_nan,High Blood Pressure_Yes,High Blood Pressure_nan,Low HDL Cholesterol_Yes,Low HDL Cholesterol_nan,High LDL Cholesterol_Yes,High LDL Cholesterol_nan,Heart Disease Status_Yes
0,56.0,153.0,NaN,0.0,24.991591,0.0,2.0,7.633228,2.0,342.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1,NaN,NaN,286.0,0.0,25.221799,2.0,0.0,8.744034,2.0,133.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,46.0,126.0,216.0,1.0,29.855447,1.0,1.0,4.440440,1.0,393.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,32.0,122.0,293.0,0.0,24.130477,1.0,0.0,5.249405,0.0,293.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,60.0,166.0,242.0,1.0,20.486289,1.0,0.0,7.030971,0.0,263.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,136.0,243.0,2.0,18.788791,2.0,0.0,6.834954,2.0,343.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
9996,38.0,172.0,154.0,2.0,31.856801,NaN,0.0,8.247784,1.0,377.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
9997,73.0,152.0,201.0,0.0,26.899911,NaN,1.0,4.436762,1.0,248.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
9998,23.0,142.0,299.0,1.0,34.964026,2.0,0.0,8.526329,2.0,113.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
9999,38.0,128.0,193.0,2.0,25.111295,0.0,2.0,5.659394,0.0,121.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0

In [405]:
newdf=newdf.dropna(ignore_index=True)

In [406]:
scale_cols = ['Age', 'Blood Pressure', 'Cholesterol Level', 'BMI', 'Sleep Hours',
       'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level',
       'Homocysteine Level']

# Perform scaling
scaler = StandardScaler()
newdf[scale_cols] = scaler.fit_transform(newdf[scale_cols])

newdf.head()

,Age,Blood Pressure,Cholesterol Level,Exercise Habits,BMI,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,...,Family Heart Disease_nan,Diabetes_Yes,Diabetes_nan,High Blood Pressure_Yes,High Blood Pressure_nan,Low HDL Cholesterol_Yes,Low HDL Cholesterol_nan,High LDL Cholesterol_Yes,High LDL Cholesterol_nan,Heart Disease Status_Yes
0,-0.179060,-1.355855,-0.203390,1.0,0.130095,1.0,1.0,-1.454719,1.0,1.637171,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,-0.945378,-1.583075,1.567832,0.0,-0.780755,1.0,0.0,-0.992040,0.0,0.487709,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.587257,0.916345,0.394685,1.0,-1.360549,1.0,0.0,0.026909,0.0,0.142871,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-1.328537,0.121075,0.739729,1.0,-0.142090,1.0,2.0,-0.845926,1.0,-1.431892,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.572523,-1.639880,-1.146508,0.0,-1.749385,2.0,2.0,1.290861,2.0,-1.650289,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [437]:
newdf.columns

Index(['Age', 'Blood Pressure', 'Cholesterol Level', 'Exercise Habits', 'BMI',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level', 'Gender_Male', 'Gender_nan',
       'Smoking_Yes', 'Smoking_nan', 'Family Heart Disease_Yes',
       'Family Heart Disease_nan', 'Diabetes_Yes', 'Diabetes_nan',
       'High Blood Pressure_Yes', 'High Blood Pressure_nan',
       'Low HDL Cholesterol_Yes', 'Low HDL Cholesterol_nan',
       'High LDL Cholesterol_Yes', 'High LDL Cholesterol_nan',
       'Heart Disease Status_Yes'],
      dtype='object')

In [439]:
# Defining the features (X) and the target (y)
X = newdf.drop('Heart Disease Status_Yes', axis=1)
y = newdf['Heart Disease Status_Yes']

# Performing the train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5759, 27), (1440, 27), (5759,), (1440,))

In [441]:
from sklearn.linear_model import LogisticRegression
Classifier = LogisticRegression()

# Train the Logistic Regression Model

Classifier.fit(X_train,y_train)

LogisticRegression()

In [443]:
#Finding the accuracy of the model
from sklearn.metrics import accuracy_score
# accuracy on training data
X_train_prediction = Classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, y_train)

print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.7982288591769404

In [445]:
X_test_prediction = Classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, y_test)

print('Accuracy on Test data : ', test_data_accuracy)

Accuracy on Test data :  0.7923611111111111

In [447]:
#Lets print the classification report
from sklearn.metrics import classification_report

print(classification_report(y_test, X_test_prediction))

              precision    recall  f1-score   support

         0.0       0.79      1.00      0.88      1141
         1.0       0.00      0.00      0.00       299

    accuracy                           0.79      1440
   macro avg       0.40      0.50      0.44      1440
weighted avg       0.63      0.79      0.70      1440

In [449]:
#Confusion matrix
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,X_test_prediction)

print(cm)

[[1141    0]
 [ 299    0]]